apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
    - name: app
      image: nginx:1.25
      volumeMounts:
        - name: data-volume
          mountPath: /usr/share/nginx/html  # 컨테이너 내 마운트 경로
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: local-pvc               # ⭐ PVC 이름
