#모든 설정을 환경변수로 주입
#apiVersion: v1
#kind: Pod
#metadata:
#  name: app-pod
#spec:
#  containers:
#    - name: app
#      image: nginx:1.25
#      envFrom:               # ⭐ ConfigMap 전체를 환경변수로
#        - configMapRef:
#            name: app-config   # ConfigMap 이름

#특정 키만 환경변수로 주입
#apiVersion: v1
#kind: Pod
#metadata:
#  name: app-pod
#spec:
#  containers:
#    - name: app
#      image: nginx:1.25
#      env:
#        - name: CUSTOM_ENV             # Pod에서 사용할 변수 이름
#          valueFrom:
#            configMapKeyRef:
#              name: app-config         # ConfigMap 이름
#              key: APP_ENV             # ConfigMap의 키

#파일로 마운트
apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
    - name: app
      image: nginx:1.25
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config       # 이 경로에 파일로 마운트
  volumes:
    - name: config-volume
      configMap:
        name: app-config